name: Databricks Bundle Deploy - dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      DATACONTRACT_DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATACONTRACT_DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup databricks CLI
        uses: databricks/setup-cli@v0.277.0

      - name: Setup datacontract CLI
        run: |
          pip install datacontract-cli[databricks]

      - name: convert to ocds
        run: |
          datacontract export fixtures/datacontract.yml --format odcs --output fixtures/conerted_odcs.yaml

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Deploy Databricks bundle
        run: databricks bundle deploy --auto-approve
