name: Databricks Bundle Deploy - dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup databricks CLI
        uses: databricks/setup-cli@v0.277.0

      - name: Setup datacontract CLI
        run: |
          # Adding pyarrow and explicitly upgrading the connector solves the 'session' bug
          pip install "datacontract-cli[databricks]" pyarrow databricks-sql-connector

      - name: convert to ocds
        run: |
          datacontract export fixtures/datacontract.yml --format odcs --output fixtures/converted_odcs.yaml
      
      - name: convert the odcs to html
        run: |
          datacontract export fixtures/odcs.yml --format html --output fixtures/contract_web_file.html

      - name: Deploy Databricks bundle
        run: databricks bundle deploy --auto-approve

      - name: test the contract on the table
        run: |
          # STRIP 'https://' - This is the most common cause of the AttributeError
          CLEAN_HOST=$(echo "${{ secrets.DATABRICKS_HOST }}" | sed -e 's|^https://||' -e 's|/$||')
          
          # Run test with hardcoded Warehouse ID path
          DATACONTRACT_DATABRICKS_SERVER_HOSTNAME=$CLEAN_HOST \
          DATACONTRACT_DATABRICKS_HTTP_PATH="/sql/1.0/warehouses/ece081f3bd7cb8a7" \
          DATACONTRACT_DATABRICKS_TOKEN="${{ secrets.DATABRICKS_TOKEN }}" \
          datacontract test fixtures/odcs.yml